# edu-course-client 配置文件

# Consul 配置
consul:
  addr: "http://47.113.220.106:8500"

# HTTP 服务器配置
server:
  port: "8080"

# 微服务配置
service:
  # 要调用的微服务名称
  addr: "edu-course"
  # 服务发现模式使用的服务名称（可选）
  name: ""
